# Serve the website: docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
# Build the website: docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material build

site_name: Parakeet
site_url: https://parakeet-nest.github.io/parakeet/
site_author: Philippe Charrière (@k33g)
site_description: >-
  🦜🪺 Parakeet is a GoLang library, made to simplify the development of small generative AI applications with Ollama 🦙.
# Repository
repo_name: parakeet-nest/parakeet
repo_url: https://github.com/parakeet-nest/parakeet

# Copyright
copyright: Copyright &copy; 2024 - 2025 Philippe Charrière

nav:
    - 🏠 Home: index.md
    - Generate completion: generate-completion.md
    - Chat completion: chat-completion.md
    - How to set the Options: set-options.md
    - Embeddings: embeddings.md
    - Chunkers & Splitters: chunkers-and-splitters.md
    - 📝🔎 Contextual Retrieval: contextual-retrieval.md
    - Parsing Markdown: parsing-markdown.md
    - Parsing Source Code: parsing-source-code.md
    - Content Helpers: content-helpers.md
    - Function Calling (before tools support): function-calling-before-tools-support.md
    - Function Calling (without tools support): function-calling-without-tools-support.md
    - Function Calling with Tools: tools.md
    - 🧾 Structured outputs: structured-outputs.md
    - WASM Plugins: wasm-plugins.md
    - Protected endpoint: protected-endpoint.md
    - 🛠️ LLMs & Parakeet Helpers: llms-helpers.md
    - 🔨 Prompt Helpers: prompt-helpers.md
    - 🧰 Tools box: tools-box.md
    - 📺 UI (Input/Print) Helpers: ui-helpers.md
    - 📺 CLI Helpers: cli-helpers.md
    - Verbose mode: verbose-mode.md
    - MCP Client: mcp.md
    - 😡 Error Handling: error-handling.md
    - OpenAI API support: openaiapi-support.md
    - 👮‍♂️ Flock agents: flock-agents.md
    - 🧪 Parakeet Examples & Recipes: parakeet-examples.md
    - 🚀 Parakeet Demos: parakeet-demos.md
    - 📝 Parakeet Blog Posts: parakeet-blog.md
 
theme:
  name: material
  palette:
    primary: deep purple

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      use_pygments: true
      auto_title: false
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences




#theme:
#    name: readthedocs
#    highlightjs: true
#    hljs_languages:
#        - yaml
#        - rust
#        - golang
#        - bash
#        - javascript