services:
  # docker compose up --build 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - LLM_CHAT=${LLM_CHAT}
    develop:
      watch:
        - action: rebuild
          path: ./backend/main.go


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 9090:8501
    environment:
      - BACKEND_SERVICE_URL=http://backend:5050
      - PAGE_TITLE=🙂🤓🥸 We are Bob!
      - PAGE_HEADER=We are legion 🤖🤖🤖
      - PAGE_ICON=🤖
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./frontend/app.py


